### ISSUE TITLE
Username already exist error in the user profile section

### ISSUE THREAD

**Issue by yassmittal** [satyambnsal/minapolis#127]
When user tries to set the username, sees a "USername already" exist message.

![photo_2024-07-17 12 28 32](https://github.com/user-attachments/assets/cd84e378-603b-4ac6-a0d1-bbc775bcbfc7)

**Comment by yassmittal** [comment]
Error from the server side 

![image](https://github.com/user-attachments/assets/3221bd29-3c77-4ba9-971b-8e2fee100870)


is exist object is returning this object

**Comment by satyambnsal** [comment]
This is fixed.
