### ISSUE TITLE
in Transactions table, transaction time column, we do not need to show the weekday

### ISSUE THREAD

**Issue by satyambnsal** [satyambnsal/minapolis#53]
Instead of Transaction time, Show age, which shows the exact date and time on tooltip hover.

Similar to this.

<img width="1417" alt="Screenshot 2024-06-17 at 7 54 49 PM" src="https://github.com/satyambnsal/minapolis/assets/13951843/6d3c59bc-b828-4196-b820-547a187867e9">

Also Transaction hash should be a hyperlink, which should open minascan link in new tab
for example, for tx hash: 5JtpBpDZV6wuMLDAipQomioiMfhqbDRhj9FqbpRvApU5gk8XX6ot
https://minascan.io/mainnet/tx/5JtpBpDZV6wuMLDAipQomioiMfhqbDRhj9FqbpRvApU5gk8XX6ot

**Comment by yassmittal** [comment]
Done!
![image](https://github.com/satyambnsal/minapolis/assets/112745526/69b3caaa-ceab-49e3-998d-ec44e94617e1)
