### ISSUE TITLE
Will need to do something of marketplace either will need to remove it or will make it dynamic!

### ISSUE THREAD

**Issue by yassmittal** [satyambnsal/minapolis#56]
![image](https://github.com/satyambnsal/minapolis/assets/112745526/80168400-0406-46ce-9711-323914d128e2)

**Comment by satyambnsal** [comment]
For marketplace, we can Show an overlay screen with coming soon section!

**Comment by yassmittal** [comment]
@satyambnsal 
![image](https://github.com/satyambnsal/minapolis/assets/112745526/cae8fbf5-3a70-4a2a-96ef-2c32c94e8c71)
How's that!

**Comment by satyambnsal** [comment]
Related to #85

**Comment by satyambnsal** [comment]
Done.
