### ISSUE TITLE
When user directly opens the Link Back button is not working.

### ISSUE THREAD

**Issue by yassmittal** [satyambnsal/minapolis#74]
![image](https://github.com/satyambnsal/minapolis/assets/112745526/439a2a64-b15b-48a4-86e4-b023f58d66d8)

When user directly opens the link for exams go to this link
https://www.tileville.xyz/competitions

directly then try to click the back button it's not working because user just landed on page and he didn't navigated yet!

**Comment by satyambnsal** [comment]
This works fine except user paste url in a new tab. for now lets close this issue.
