### ISSUE TITLE
Make the Voucher code functionality

### ISSUE THREAD

**Issue by yassmittal** [satyambnsal/minapolis#75]
**On The Entry fee modal, we will show a simple line like 
Have a voucher code ?
If user clicks it, We should show an Input box just below it and redeem button below the inout box**

**Comment by satyambnsal** [comment]
Voucher codes table will have a following field.

id (Primary Key)
code (Unique)
is_redeemed
redeemed_by (Foreign Key to users table, nullable)
redeemed_at (Timestamp, nullable)
competition_id (Foreign Key to competitions table, nullable if usable for any competition)
expiry_date
created_at

**Comment by satyambnsal** [comment]
this is done.
