### ISSUE TITLE
Bugs in pay participation Fees Modal

### ISSUE THREAD

**Issue by yassmittal** [satyambnsal/minapolis#78]
If the user doesn't have wallet installed in the browser he can't play even the free game or voucher redeemed game.

**Comment by yassmittal** [comment]
![telegram-cloud-photo-size-5-6321136595293552794-x](https://github.com/satyambnsal/minapolis/assets/112745526/16b95f0f-c977-49f7-a154-39c196d3ee63)

**Comment by satyambnsal** [comment]
Not relevant any more.
